{% set name = "tiledb" %}
{% set version = "0.32.5" %}

package:
  name: tiledb-py
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: faa507115731742e4eb0fbfec7be41310efcc46523afc188440b2d26ed48d361

build:
  number: 0
  # Windows skip is due to snowflake only build of tiledb 2.26.2
  skip: True  # [py<39 or s390x or win]
  ignore_run_exports:
    - numpy

requirements:
  build:
    - pybind11
    - cmake >=3.15
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - wheel
    - setuptools
    - setuptools-scm
    - scikit-build-core
    - python
    - cython >=3
    - numpy >=2.0.1
    - pybind11
    - tiledb >=2.26
  run:
    - python
    - packaging

{% if python_impl != 'pypy' %}
test:
  requires:
    - hypothesis
    - pyarrow
    - pytest
    - pandas
    - psutil
    - pip
  imports:
    - tiledb
  source_files:
    - tiledb/tests/
  commands:
    - pip check
    - python -c "import tiledb; tiledb.libtiledb.version()"
    - python -c "import tiledb; assert not tiledb.VFS().supports('s3')" # we don't support backends in this build
    - pytest -v --ignore-glob='*_examples.py' --ignore-glob='*_dask.py'
{% endif %}

about:
  home: https://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface to the TileDB sparse and dense multi-dimensional array storage manager
  description: |
    TileDB-Py is the python interface to the TileDB array storage manager.
    TileDB  is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can store dense and sparse array data with
    support for fast reads and updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: https://tiledb-inc-tiledb.readthedocs-hosted.com/projects/tiledb-py/en/stable/python-api.html
  dev_url: https://github.com/TileDB-Inc/TileDB-Py

extra:
  recipe-maintainers:
    - dudoslav
    - ihnorton
    - jdblischak
    - shelnutt2
    - nguyenv
    - johnkerl
    - kounelisagis
